# hypridle - regras de inatividade (notebook)

general {
    lock_cmd = pidof hyprlock || hyprlock
    before_sleep_cmd = loginctl lock-session
    after_sleep_cmd = hyprctl dispatch dpms on
    ignore_dbus_inhibit = false
}

# 2min30 -> escurece a tela (guarda o brilho anterior)
listener {
    timeout = 150
    on-timeout = brightnessctl -s set 10
    on-resume = brightnessctl -r
}

# 2min30 -> apaga o LED do teclado, se existir
listener {
    timeout = 150
    on-timeout = brightnessctl -sd rgb:kbd_backlight set 0
    on-resume = brightnessctl -rd rgb:kbd_backlight
}

# 5min -> bloqueia
listener {
    timeout = 300
    on-timeout = loginctl lock-session
}

# 5min30 -> desliga a tela
listener {
    timeout = 330
    on-timeout = hyprctl dispatch dpms off
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

# 30min -> suspende
listener {
    timeout = 1800
    on-timeout = systemctl suspend
}
